"""initial_schema

Migración consolidada que reemplaza las 15 migraciones anteriores (2026-03 a 2026-07,
desde db5ece233ada hasta 94c9b6697c6b). Producida autogenerando contra los modelos
actuales sobre una base de datos vacía, y verificada por diff de `pg_dump --schema-only`
contra el schema resultante de aplicar el historial viejo completo — son estructuralmente
idénticos. Los dos triggers de integridad de `invoices.folder_status_id` (no representables
en SQLAlchemy) se agregaron a mano al final de `upgrade()`, copiados verbatim de la antigua
`a7f3b1e2c8d5_add_invoice_status_integrity_triggers.py`.

Revision ID: 05e49443f9b5
Revises:
Create Date: 2026-07-04 16:50:31.958619

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e49443f9b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(length=300), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_name')
    )
    op.create_table('contract_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(length=300), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_name')
    )
    op.create_table('doc_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('folder_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('invoice_id_prefix', sa.String(length=20), nullable=True),
    sa.Column('sihos_base_url', sa.String(length=500), nullable=True),
    sa.Column('sihos_doc_code', sa.String(length=20), nullable=True),
    sa.Column('sihos_user', sa.String(length=200), nullable=True),
    sa.Column('sihos_password', sa.String(length=200), nullable=True),
    sa.Column('drive_credentials_enc', sa.String(length=10000), nullable=True),
    sa.Column('logo_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('logo_content_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('prefix_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wrong_prefix', sa.String(length=20), nullable=False),
    sa.Column('correct_prefix', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wrong_prefix')
    )
    op.create_table('service_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('administrator_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('contract_type_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrators.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contract_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('administrator_id', 'contract_id')
    )
    op.create_table('audit_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('period_label', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'date_from', 'date_to', 'period_label')
    )
    op.create_table('service_type_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('doc_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doc_type_id'], ['doc_types.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'service_type_id', 'doc_type_id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('raw_service', sa.String(length=300), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'raw_service')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_period_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id_type', sa.String(length=10), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=False),
    sa.Column('patient_name', sa.String(length=300), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=True),
    sa.Column('service_type_id', sa.Integer(), nullable=True),
    sa.Column('employee', sa.String(length=200), nullable=True),
    sa.Column('admission', sa.String(length=50), nullable=True),
    sa.Column('folder_status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['audit_period_id'], ['audit_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_status_id'], ['folder_statuses.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_period_id', 'invoice_number')
    )
    op.create_index('ix_invoices_agreement_id', 'invoices', ['agreement_id'], unique=False)
    op.create_index('ix_invoices_audit_period_id', 'invoices', ['audit_period_id'], unique=False)
    op.create_index('ix_invoices_folder_status_id', 'invoices', ['folder_status_id'], unique=False)
    op.create_index('ix_invoices_service_type_id', 'invoices', ['service_type_id'], unique=False)
    op.create_table('missing_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('doc_type_id', sa.Integer(), nullable=False),
    sa.Column('expected_path', sa.String(length=500), nullable=False),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_type_id'], ['doc_types.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'doc_type_id')
    )
    # ### end Alembic commands ###

    # --- Triggers de integridad de estado de factura (no representables en SQLAlchemy) ---
    op.execute("""
        CREATE OR REPLACE FUNCTION sync_invoice_status_from_findings()
        RETURNS TRIGGER AS $$
        DECLARE
            v_invoice_id    INTEGER;
            v_current_id    INTEGER;
            v_presente_id   INTEGER;
            v_pendiente_id  INTEGER;
            v_open_count    INTEGER;
        BEGIN
            -- Determine the affected invoice_id for each DML type
            IF TG_OP = 'DELETE' THEN
                v_invoice_id := OLD.invoice_id;
            ELSE
                v_invoice_id := NEW.invoice_id;
            END IF;

            -- Resolve status IDs
            SELECT id INTO v_presente_id  FROM folder_statuses WHERE status = 'PRESENTE';
            SELECT id INTO v_pendiente_id FROM folder_statuses WHERE status = 'PENDIENTE';

            -- Get current status of the invoice
            SELECT folder_status_id INTO v_current_id
            FROM invoices WHERE id = v_invoice_id;

            -- Only manage PRESENTE / PENDIENTE — leave other statuses alone
            IF v_current_id NOT IN (v_presente_id, v_pendiente_id) THEN
                RETURN NEW;
            END IF;

            -- Count remaining unresolved findings for this invoice
            SELECT COUNT(*) INTO v_open_count
            FROM missing_files
            WHERE invoice_id = v_invoice_id AND resolved_at IS NULL;

            IF v_open_count > 0 AND v_current_id = v_presente_id THEN
                UPDATE invoices
                SET folder_status_id = v_pendiente_id
                WHERE id = v_invoice_id;
            ELSIF v_open_count = 0 AND v_current_id = v_pendiente_id THEN
                UPDATE invoices
                SET folder_status_id = v_presente_id
                WHERE id = v_invoice_id;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER trg_sync_invoice_status_from_findings
        AFTER INSERT OR UPDATE OR DELETE ON missing_files
        FOR EACH ROW EXECUTE FUNCTION sync_invoice_status_from_findings();
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION guard_invoice_presente_status()
        RETURNS TRIGGER AS $$
        DECLARE
            v_presente_id   INTEGER;
            v_pendiente_id  INTEGER;
        BEGIN
            SELECT id INTO v_presente_id  FROM folder_statuses WHERE status = 'PRESENTE';
            SELECT id INTO v_pendiente_id FROM folder_statuses WHERE status = 'PENDIENTE';

            -- Only intercept attempts to set status to PRESENTE
            IF NEW.folder_status_id = v_presente_id THEN
                IF EXISTS (
                    SELECT 1 FROM missing_files
                    WHERE invoice_id = NEW.id AND resolved_at IS NULL
                ) THEN
                    -- Silently correct to PENDIENTE instead of raising an error
                    NEW.folder_status_id := v_pendiente_id;
                END IF;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER trg_guard_invoice_presente_status
        BEFORE UPDATE OF folder_status_id ON invoices
        FOR EACH ROW EXECUTE FUNCTION guard_invoice_presente_status();
    """)


def downgrade() -> None:
    # --- Triggers de integridad (deben borrarse antes que las tablas que referencian) ---
    op.execute("DROP TRIGGER IF EXISTS trg_guard_invoice_presente_status ON invoices")
    op.execute("DROP FUNCTION IF EXISTS guard_invoice_presente_status()")
    op.execute("DROP TRIGGER IF EXISTS trg_sync_invoice_status_from_findings ON missing_files")
    op.execute("DROP FUNCTION IF EXISTS sync_invoice_status_from_findings()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missing_files')
    op.drop_index('ix_invoices_service_type_id', table_name='invoices')
    op.drop_index('ix_invoices_folder_status_id', table_name='invoices')
    op.drop_index('ix_invoices_audit_period_id', table_name='invoices')
    op.drop_index('ix_invoices_agreement_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('services')
    op.drop_table('service_type_documents')
    op.drop_table('audit_periods')
    op.drop_table('agreements')
    op.drop_table('service_types')
    op.drop_table('prefix_corrections')
    op.drop_table('institutions')
    op.drop_table('folder_statuses')
    op.drop_table('doc_types')
    op.drop_table('contracts')
    op.drop_table('contract_types')
    op.drop_table('administrators')
    # ### end Alembic commands ###
