HOSPITALS = {
    "SANTA_LUCIA": {
        "NIT": "890701078",
        "INVOICE_IDENTIFIER_PREFIX": "HSL",
        "SIHOS_BASE_URL": "http://181.79.85.36:82/sihos",
        "SIHOS_INVOICE_DOC_CODE": "FV",
        "DOCUMENT_STANDARDS": {
            "FACTURA": "FEV",
            "FIRMA": "CRC",
            "VALIDACION": "OPF",
            "HISTORIA": ["EPI", "HEV", "HAO", "HAU"],
            "RESULTADOS": "PDX",
            "BITACORA": "TAP",
            "RESOLUCION": "LDP",
            "MEDICAMENTOS": "HAM",
            "AUTORIZACION": "PDE",
        },
        "MISNAMED_FIXER_MAP": {
            "OPD": "OPF",
            "FVE": "FEV",
            "FHEV": "HEV",
            "OHEV": "HEV",
            "FOPF": "OPF",
            "OPG": "OPF",
            "FVS": "FEV",
            "FEPI": "EPI",
            "HVE": "HEV",
        },
    },
    "RAMON_MARIA_ARANA": {
        "NIT": "809001159",
        "INVOICE_IDENTIFIER_PREFIX": "FE",
        "SIHOS_BASE_URL": "http://181.79.89.117:8181/sihos",
        "SIHOS_INVOICE_DOC_CODE": "FE",
        "DOCUMENT_STANDARDS": {
            "FACTURA": "FEV",
            "FIRMA": "CRC",
            "VALIDACION": "OPF",
            "HISTORIA": ["EPI", "HEV", "HAO", "HAU"],
            "RESULTADOS": "PDX",
            "BITACORA": "TAP",
            "RESOLUCION": "LDP",
            "MEDICAMENTOS": "HAM",
            "AUTORIZACION": "PDE",
        },
        "MISNAMED_FIXER_MAP": {},
    },
}
